### ISSUE TITLE
What the data-set and images should look like?

### ISSUE THREAD

**Issue by ghost** [grohith327/simplegan#3]
What the data-set and images should look like? I am just starting to work with _**GANs**_.
```
Loading images: 0it [00:00, ?it/s]
Traceback (most recent call last):
  File "C:/Users/Vlad/OneDrive/Projects/GANs/test.py", line 4, in <module>
    train_data = gan.load_data(data_dir="./input_data", batch_size=2)
  File "C:\Users\Vlad\Anaconda3\envs\GANs\lib\site-packages\simplegan\gan\sagan.py", line 138, in load_data
    train_data, train_labels = load_custom_data_with_labels(data_dir, img_shape)
  File "C:\Users\Vlad\Anaconda3\envs\GANs\lib\site-packages\simplegan\datasets\load_custom_data.py", line 153, in load_custom_data_with_labels
    assert len(train_data) > 0, "No images to load from directory"
AssertionError: No images to load from directory
```

**Comment by grohith327** [comment]
The seems to be no images to load from the directory. Ensure the directory is of the following structure: 
```
 input_data 
    -label 1(int type) 
      -*.jpg 
    -label 2(int type) 
      -*.jpg 
    ...
```

Note: In case you do not want to restructure the directory, you can load the data on your own and generate `tf.data` objects, which you can use to train the model.
